platform :ios, '13.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'BikeForLife' do
 config = use_native_modules!


  # Pods for BikeForLife
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )



  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  target 'BikeForLifeTests' do
    inherit! :complete
    # Pods for testing
  end

 # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

   post_install do |installer|
      react_native_post_install(installer)

  end

end
